:bug: makes cli write to stdout in little chunks
I bumped into a bug now and then with a package, where piping the output
to (e.g.) graphviz dot would barf on me with an error message like

	Error: <stdin>: syntax error in line 72 scanning a quoted string
	(missing endquote? longer than 16384?)

Some puzzling things:
- The size of the scanned tree and the corresponding size
  of the output didn't seem to matter.
- Writing the output to file _with the same parameters_ worked fine.
- Likewise when _redirecting_ to a file (instead of first running it
  through a pipe)

Today I encountered a package (atom-state-machine-cat-preview) on which
I could reliably reproduce the problem. (`depcruise -v -T dot lib spec |
dot -T svg > tmp_deps.svg')

Inspecting the output (by piping it through `cat` ...) learned that the
output was chopped off at 65536 bytes. Aha! So the naively using
process.stdout.write(pContent) to write the whole shebang bumped into a
limit. Probably something with a pipe.

Some DuckDuckGo queriese and some beard-scratching later I found the
answer:
- on my machine the max _guaranteed_ pipe bufffer size is 512 bytes
 (`ulimit -a`: `pipe size            (512 bytes, -p) 1`).
- so, probably writing in chunks of 512 should solve, and if not,
  alleviate the problem.
- So I implemented that: :boom: problem gone.
- When I tried somewhat larger buffer sizes (4096 - something I
  encountered on the internet somewhere, or even 1024) on the same data
  set the problem occurred again.

(This is possibly the largest commit message I ever wrote. For those
reading this: sorry, I was in a hurry ...)